INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("A","Alameda");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("A V","Avenida Marginal Direita");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AC","Avenida Marginal Esquerda");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ACA","Anel Viário");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ACL","Antiga Estrada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AD","Artéria");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AE","Alto");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AER","Atalho");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AL","Avenida");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AMD","Avenida Contorno");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AME","Avenida Marginal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AN","Avenida Velha");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ANT","Balneário");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ART","Beco");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AT","Buraco");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ATL","Belvedere");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AV","Bloco");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AVC","Balão");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AVM","Blocos");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("AVV","Bulevar");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BAL","Bosque");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BC","Boulevard");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BCO","Baixa");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BEL","Cais");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BL","Calçada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BLO","Caminho");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BLS","Canal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BLV","Chácara");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BSQ","Chapadão");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BVD","Ciclovia");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("BX","Circular");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("C","Conjunto");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CAL","Conjunto Mutirão");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CAM","Complexo Viário");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CAN","Colônia");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CH","Comunidade");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CHA","Condomínio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CIC","Corredor");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CIR","Campo");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CJ","Córrego");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CJM","Contorno");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CMP","Descida");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("COL","Desvio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("COM","Distrito");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CON","Entre Bloco");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("COR","Estrada Intermunicipal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CPO","Enseada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CRG","Entrada Particular");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("CTN","Entre Quadra");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("DSC","Escada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("DSV","Escadaria");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("DT","Estrada Estadual");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EB","Estrada Vicinal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EIM","Estrada de Ligação");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ENS","Estrada Municipal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ENT","Esplanada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EQ","Estrada de Servidão");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESC","Estrada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESD","Estrada Velha");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESE","Estrada Antiga");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESI","Estação");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESL","Estádio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESM","Estância");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESP","Estrada Particular");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESS","Estacionamento");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EST","Evangélica");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ESV","Elevada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ETA","Eixo Industrial");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ETC","Favela");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ETD","Fazenda");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ETN","Ferrovia");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ETP","Fonte");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ETT","Feira");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EVA","Forte");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EVD","Galeria");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("EX","Granja");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("FAV","Núcleo Habitacional");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("FAZ","Ilha");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("FER","Indeterminado");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("FNT","Ilhota");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("FRA","Jardim");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("FTE","Jardinete");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("GAL","Ladeira");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("GJA","Lagoa");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("HAB","Lago");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("IA","Loteamento");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("IND","Largo");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("IOA","Lote");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("JD","Mercado");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("JDE","Marina");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("LD","Modulo");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("LGA","Projeção");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("LGO","Morro");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("LOT","Monte");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("LRG","Núcleo");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("LT","Núcleo Rural");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("MER","Outeiro");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("MNA","Paralela");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("MOD","Passeio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("MRG","Pátio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("MRO","Praça");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("MTE","Praça de Esportes");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("NUC","Parada");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("NUR","Paradouro");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("OUT","Ponta");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PAR","Praia");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PAS","Prolongamento");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PAT","Parque Municipal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PC","Parque");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PCE","Parque Residencial");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PDA","Passarela");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PDO","Passagem");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PNT","Passagem de Pedestre");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PR","Passagem Subterrânea");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PRL","Ponte");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PRM","Porto");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PRQ","Quadra");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PRR","Quinta");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PSA","Quintas");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PSG","Rua");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PSP","Rua Integração");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PSS","Rua de Ligação");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PTE","Rua Particular");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("PTO","Rua Velha");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("Q","Ramal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("QTA","Recreio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("QTS","Recanto");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("R","Retiro");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("R I","Residencial");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("R L","Reta");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("R P","Ruela");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("R V","Rampa");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RAM","Rodo Anel");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RCR","Rodovia");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("REC","Rua de Pedestre");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RER","Margem");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RES","Retorno");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RET","Rotatória");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RLA","Segunda Avenida");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RMP","Sitio");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ROA","Servidão");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ROD","Setor");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RPE","Subida");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RPR","Trincheira");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RTN","Terminal");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("RTT","Trecho");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("SEG","Trevo");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("SIT","Túnel");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("SRV","Travessa");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ST","Travessa Particular");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("SUB","Travessa Velha");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TCH","Unidade");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TER","Via");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TR","Via Coletora");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TRV","Via Local");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TUN","Via Expressa");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TV","Via de Acesso");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TVP","Vala");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("TVV","Via Costeira");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("UNI","Viaduto");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("V","Vereda");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("V C","Via Elevado");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VCO","Via de Pedestre");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VD","Variante");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VEV","Via Elevado");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VL","Vila");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VLA","Viela");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VLE","Vale");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VLT","Via Litorânea");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VPE","Via de Pedestre");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("VRT","Variante");
INSERT INTO tipologradouro (cdtiplog, descricao) VALUES ("ZIG","Zigue-Zague");